name = "day6"
description = "Shiny new project"
version = "0.0.0"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]

executables = ["day6"]

[[depends-on]]
aoc2021 = "*"

[[pins]]
aoc2021 = { path = "../aoc2021" }
