name = "day11"
description = "Shiny new project"
version = "0.0.0"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]

executables = ["day11"]

[[depends-on]]
aoc2021 = "*"
components = "*"

[[pins]]
aoc2021 = { path = "../aoc2021" }
components = { path = "../../components" }
