name = "day23"
description = "day 23 of the 2021 Advent of Code"
version = "0.1.0-dev"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["advent-of-code", "ada"]

executables = ["day23"]
